import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'

export default function Home() {

  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center flex-col h-screen space-y-10">
        <Image src={"/logo-dark.svg"} width={140} height={140} alt="Image Main" />
        <div className='flex items-center justify-center flex-col space-y-6'>
          <button onClick={() => router.push("login")} className='w-[250px] py-2 px-20 bg-[#42BEA5] rounded-lg'>
            Login
          </button>
          <button onClick={() => router.push("login")} className='w-[250px] py-2 px-20 bg-white rounded-lg'>
            Register
          </button>
        </div>
      </main>
    </>
  )
}
